sliders:
  slider1:
    - "master"
  slider2:
    - "msedge.exe"
    - "chrome.exe"
  slider3:
    - "Palworld.exe"
    - "Palworld-Win64-Shipping.exe"
  slider4:
    - "discord.exe"
COMPort:
  "COM4"
Baud:
  115200