sliders:
  slider1:
    - "msedge.exe"
  slider2:
    - "Palworld.exe"
    - "Palworld-Win64-Shipping.exe"
  slider3:
    - "None"
  slider4:
    - "None"
COMPort:
  "COM4"
Baud:
  115200
UpdateSpeed:
  0.1